# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(default=None, max_length=10000),
            preserve_default=False,
        ),
    ]
