# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_office',
            new_name='office',
        ),
    ]
