# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='specialty_department',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='user',
        ),
    ]
