# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_appointment_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='office',
        ),
    ]
