# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_appointment_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='office',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
